project_library(game)
project_library_sources(
	controller.h
	editor.h
	editor.cpp
	enemy.h
	enemy.cpp
	enemyarchetype.h
	enemyarchetype.cpp
	instance.h
	instance.cpp
	inventory.h
	inventory.cpp
	item.h
	itemtype.h
	gamesystem.h
	gameplaysystem.h
	gameplaysystem.cpp
	healthsystem.h
	healthsystem.cpp
	checkpointsystem.h
	checkpointsystem.cpp
	interactionsystem.h
	interactionsystem.cpp
	projectilesystem.h
	projectilesystem.cpp
	runtimelayer.h
	runtimelayer.cpp
	rifle.h
	rifle.cpp
	melee.h
	melee.cpp
	player.h
	player.cpp
	projectile.h
	projectile.cpp
	spawner.h
	spawner.cpp
	spritereader.h
	spritereader.cpp
	weapon.h
	weapontype.h
)

add_subdirectory(controller)

target_link_libraries(game PUBLIC 
	core
	scene
	physics
)
