project_library(core)
project_library_sources(
  ansi.h
	application.h
	application.cpp
	assert.h
	buffer.h
	class.h
	core.h
	core.cpp
	delegate.h
	layer.h
	layer.cpp
	layerstack.h
	layerstack.cpp
	log.h
	log_formatters.h
	macros.h
	object.h
	platform.h
	profiler.h
	profiler.cpp
	selectioncontext.h
	selectioncontext.cpp
	settings.h
	settings.cpp
	string.h
	template.h
	thread.h
	thread.cpp
	timer.h
	uuid.h
	uuid.cpp
	window.h
	window.cpp
)

add_subdirectory(event)
add_subdirectory(input)
add_subdirectory(math)
